-- https://programmers.co.kr/learn/courses/30/lessons/59044
SELECT x.* FROM(
    SELECT NAME, DATETIME FROM ANIMAL_INS
    MINUS
    SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME
    FROM ANIMAL_INS
    inner join ANIMAL_OUTS
    on ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    ORDER BY DATETIME
) x
where ROWNUM BETWEEN 1 AND 3