-- 코드를 입력하세요
SELECT * FROM(
    SELECT TO_CHAR(DATETIME,'HH24') as HOUR, COUNT(TO_CHAR(DATETIME,'HH24')) as COUNT FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME,'HH24')
    ORDER BY TO_CHAR(DATETIME,'HH24')
)
WHERE HOUR BETWEEN 9 AND 19;